spring:
  application:
    name: salus-event-engine-management
  jackson:
    mapper:
      default-view-inclusion: true
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}