spring:
  jackson:
    mapper:
      default-view-inclusion: true
  zipkin:
    enabled: false
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management.endpoints.web.exposure.include: "health,jolokia,metrics,loggers"
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}
